sudo: false
language: scala
scala: 2.11.8
jdk: oraclejdk8
script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
branches:
  only:
    - master
    - 2.4.x
after_success:
  - bash <(curl -s https://codecov.io/bash)
